# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Mon Feb 11 17:44:53 2019
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(980, 851)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8("#centralwidget {\n"
"    background-image: url(:/images/background.png);\n"
"}\n"
"\n"
"\n"
"\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayout = QtGui.QFormLayout(self.centralwidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_3)
        self.mainMenu = QtGui.QStackedWidget(self.centralwidget)
        self.mainMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.mainMenu.setStyleSheet(_fromUtf8("background-color: rgb(108, 108, 108);"))
        self.mainMenu.setObjectName(_fromUtf8("mainMenu"))
        self.login_register = QtGui.QWidget()
        self.login_register.setObjectName(_fromUtf8("login_register"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.login_register)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_4)
        self.label = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.txtEmail = QtGui.QLineEdit(self.login_register)
        self.txtEmail.setAutoFillBackground(False)
        self.txtEmail.setObjectName(_fromUtf8("txtEmail"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtEmail)
        self.label_19 = QtGui.QLabel(self.login_register)
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_19)
        self.label_2 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txtPassword = QtGui.QLineEdit(self.login_register)
        self.txtPassword.setAutoFillBackground(False)
        self.txtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtPassword)
        self.label_18 = QtGui.QLabel(self.login_register)
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_18)
        self.btnLogin = QtGui.QPushButton(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName(_fromUtf8("btnLogin"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.btnLogin)
        self.label_15 = QtGui.QLabel(self.login_register)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_15)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_6 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_6)
        self.label_20 = QtGui.QLabel(self.login_register)
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_20)
        self.label_7 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.txtNewEmail = QtGui.QLineEdit(self.login_register)
        self.txtNewEmail.setAutoFillBackground(False)
        self.txtNewEmail.setObjectName(_fromUtf8("txtNewEmail"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtNewEmail)
        self.label_24 = QtGui.QLabel(self.login_register)
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_24)
        self.label_8 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txtNickname = QtGui.QLineEdit(self.login_register)
        self.txtNickname.setAutoFillBackground(False)
        self.txtNickname.setObjectName(_fromUtf8("txtNickname"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtNickname)
        self.label_25 = QtGui.QLabel(self.login_register)
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_25)
        self.label_9 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_9)
        self.txtNewPassword = QtGui.QLineEdit(self.login_register)
        self.txtNewPassword.setAutoFillBackground(False)
        self.txtNewPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtNewPassword.setObjectName(_fromUtf8("txtNewPassword"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.txtNewPassword)
        self.label_17 = QtGui.QLabel(self.login_register)
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.label_17)
        self.btnRegister = QtGui.QPushButton(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnRegister.setFont(font)
        self.btnRegister.setObjectName(_fromUtf8("btnRegister"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.btnRegister)
        self.horizontalLayout_5.addLayout(self.formLayout_3)
        self.mainMenu.addWidget(self.login_register)
        self.single_or_multi = QtGui.QWidget()
        self.single_or_multi.setObjectName(_fromUtf8("single_or_multi"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.single_or_multi)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.single_player_layout = QtGui.QVBoxLayout()
        self.single_player_layout.setObjectName(_fromUtf8("single_player_layout"))
        self.label_5 = QtGui.QLabel(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.single_player_layout.addWidget(self.label_5)
        self.btnLoadNewSingle = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnLoadNewSingle.setFont(font)
        self.btnLoadNewSingle.setObjectName(_fromUtf8("btnLoadNewSingle"))
        self.single_player_layout.addWidget(self.btnLoadNewSingle)
        self.btnLoadContSingle = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnLoadContSingle.setFont(font)
        self.btnLoadContSingle.setObjectName(_fromUtf8("btnLoadContSingle"))
        self.single_player_layout.addWidget(self.btnLoadContSingle)
        self.horizontalLayout.addLayout(self.single_player_layout)
        self.multi_player_layout = QtGui.QVBoxLayout()
        self.multi_player_layout.setObjectName(_fromUtf8("multi_player_layout"))
        self.label_10 = QtGui.QLabel(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.multi_player_layout.addWidget(self.label_10)
        self.btnLoadJoinMulti = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnLoadJoinMulti.setFont(font)
        self.btnLoadJoinMulti.setObjectName(_fromUtf8("btnLoadJoinMulti"))
        self.multi_player_layout.addWidget(self.btnLoadJoinMulti)
        self.btnLoadHostMulti = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnLoadHostMulti.setFont(font)
        self.btnLoadHostMulti.setObjectName(_fromUtf8("btnLoadHostMulti"))
        self.multi_player_layout.addWidget(self.btnLoadHostMulti)
        self.btnLoadContMulti = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnLoadContMulti.setFont(font)
        self.btnLoadContMulti.setObjectName(_fromUtf8("btnLoadContMulti"))
        self.multi_player_layout.addWidget(self.btnLoadContMulti)
        self.horizontalLayout.addLayout(self.multi_player_layout)
        self.mainMenu.addWidget(self.single_or_multi)
        self.new_single = QtGui.QWidget()
        self.new_single.setObjectName(_fromUtf8("new_single"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.new_single)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = QtGui.QLabel(self.new_single)
        self.label_11.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_12 = QtGui.QLabel(self.new_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_3.addWidget(self.label_12)
        self.lstChooseMapNewSingle = QtGui.QListView(self.new_single)
        self.lstChooseMapNewSingle.setObjectName(_fromUtf8("lstChooseMapNewSingle"))
        self.verticalLayout_3.addWidget(self.lstChooseMapNewSingle)
        self.btnNewSingle = QtGui.QPushButton(self.new_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnNewSingle.setFont(font)
        self.btnNewSingle.setObjectName(_fromUtf8("btnNewSingle"))
        self.verticalLayout_3.addWidget(self.btnNewSingle)
        self.btnBackNewSingle = QtGui.QPushButton(self.new_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnBackNewSingle.setFont(font)
        self.btnBackNewSingle.setObjectName(_fromUtf8("btnBackNewSingle"))
        self.verticalLayout_3.addWidget(self.btnBackNewSingle)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblMapNewSingle = QtGui.QLabel(self.new_single)
        self.lblMapNewSingle.setMinimumSize(QtCore.QSize(300, 0))
        self.lblMapNewSingle.setText(_fromUtf8(""))
        self.lblMapNewSingle.setObjectName(_fromUtf8("lblMapNewSingle"))
        self.verticalLayout_2.addWidget(self.lblMapNewSingle)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.mainMenu.addWidget(self.new_single)
        self.continue_single = QtGui.QWidget()
        self.continue_single.setObjectName(_fromUtf8("continue_single"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.continue_single)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_13 = QtGui.QLabel(self.continue_single)
        self.label_13.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_14 = QtGui.QLabel(self.continue_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_6.addWidget(self.label_14)
        self.lstChooseGameContSingle = QtGui.QListView(self.continue_single)
        self.lstChooseGameContSingle.setObjectName(_fromUtf8("lstChooseGameContSingle"))
        self.verticalLayout_6.addWidget(self.lstChooseGameContSingle)
        self.btnContSingle = QtGui.QPushButton(self.continue_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnContSingle.setFont(font)
        self.btnContSingle.setObjectName(_fromUtf8("btnContSingle"))
        self.verticalLayout_6.addWidget(self.btnContSingle)
        self.btnBackContSingle = QtGui.QPushButton(self.continue_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnBackContSingle.setFont(font)
        self.btnBackContSingle.setObjectName(_fromUtf8("btnBackContSingle"))
        self.verticalLayout_6.addWidget(self.btnBackContSingle)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.lblMapContinueSingle = QtGui.QLabel(self.continue_single)
        self.lblMapContinueSingle.setMinimumSize(QtCore.QSize(300, 0))
        self.lblMapContinueSingle.setText(_fromUtf8(""))
        self.lblMapContinueSingle.setObjectName(_fromUtf8("lblMapContinueSingle"))
        self.horizontalLayout_4.addWidget(self.lblMapContinueSingle)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.mainMenu.addWidget(self.continue_single)
        self.join_multi = QtGui.QWidget()
        self.join_multi.setObjectName(_fromUtf8("join_multi"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.join_multi)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblMapJoinMulti = QtGui.QLabel(self.join_multi)
        self.lblMapJoinMulti.setMinimumSize(QtCore.QSize(300, 0))
        self.lblMapJoinMulti.setText(_fromUtf8(""))
        self.lblMapJoinMulti.setObjectName(_fromUtf8("lblMapJoinMulti"))
        self.horizontalLayout_6.addWidget(self.lblMapJoinMulti)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_21 = QtGui.QLabel(self.join_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_7.addWidget(self.label_21)
        self.lstChooseGameJoinMulti = QtGui.QListView(self.join_multi)
        self.lstChooseGameJoinMulti.setObjectName(_fromUtf8("lstChooseGameJoinMulti"))
        self.verticalLayout_7.addWidget(self.lstChooseGameJoinMulti)
        self.btnJoinMulti = QtGui.QPushButton(self.join_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnJoinMulti.setFont(font)
        self.btnJoinMulti.setObjectName(_fromUtf8("btnJoinMulti"))
        self.verticalLayout_7.addWidget(self.btnJoinMulti)
        self.btnBackJoinMulti = QtGui.QPushButton(self.join_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnBackJoinMulti.setFont(font)
        self.btnBackJoinMulti.setObjectName(_fromUtf8("btnBackJoinMulti"))
        self.verticalLayout_7.addWidget(self.btnBackJoinMulti)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.label_16 = QtGui.QLabel(self.join_multi)
        self.label_16.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_6.addWidget(self.label_16)
        self.mainMenu.addWidget(self.join_multi)
        self.new_multi = QtGui.QWidget()
        self.new_multi.setObjectName(_fromUtf8("new_multi"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.new_multi)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_26 = QtGui.QLabel(self.new_multi)
        self.label_26.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_8.addWidget(self.label_26)
        self.txtPlayer1 = QtGui.QLineEdit(self.new_multi)
        self.txtPlayer1.setObjectName(_fromUtf8("txtPlayer1"))
        self.verticalLayout_8.addWidget(self.txtPlayer1)
        self.txtPlayer2 = QtGui.QLineEdit(self.new_multi)
        self.txtPlayer2.setObjectName(_fromUtf8("txtPlayer2"))
        self.verticalLayout_8.addWidget(self.txtPlayer2)
        self.txtPlayer3 = QtGui.QLineEdit(self.new_multi)
        self.txtPlayer3.setObjectName(_fromUtf8("txtPlayer3"))
        self.verticalLayout_8.addWidget(self.txtPlayer3)
        self.txtPlayer4 = QtGui.QLineEdit(self.new_multi)
        self.txtPlayer4.setObjectName(_fromUtf8("txtPlayer4"))
        self.verticalLayout_8.addWidget(self.txtPlayer4)
        self.txtPlayer5 = QtGui.QLineEdit(self.new_multi)
        self.txtPlayer5.setObjectName(_fromUtf8("txtPlayer5"))
        self.verticalLayout_8.addWidget(self.txtPlayer5)
        self.txtPlayer6 = QtGui.QLineEdit(self.new_multi)
        self.txtPlayer6.setObjectName(_fromUtf8("txtPlayer6"))
        self.verticalLayout_8.addWidget(self.txtPlayer6)
        self.txtPlayer7 = QtGui.QLineEdit(self.new_multi)
        self.txtPlayer7.setObjectName(_fromUtf8("txtPlayer7"))
        self.verticalLayout_8.addWidget(self.txtPlayer7)
        self.txtPlayer8 = QtGui.QLineEdit(self.new_multi)
        self.txtPlayer8.setObjectName(_fromUtf8("txtPlayer8"))
        self.verticalLayout_8.addWidget(self.txtPlayer8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_23 = QtGui.QLabel(self.new_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_5.addWidget(self.label_23)
        self.lstChooseMapNewMulti = QtGui.QListView(self.new_multi)
        self.lstChooseMapNewMulti.setObjectName(_fromUtf8("lstChooseMapNewMulti"))
        self.verticalLayout_5.addWidget(self.lstChooseMapNewMulti)
        self.btnStartNewMulti = QtGui.QPushButton(self.new_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnStartNewMulti.setFont(font)
        self.btnStartNewMulti.setObjectName(_fromUtf8("btnStartNewMulti"))
        self.verticalLayout_5.addWidget(self.btnStartNewMulti)
        self.btnBackNewMulti = QtGui.QPushButton(self.new_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnBackNewMulti.setFont(font)
        self.btnBackNewMulti.setObjectName(_fromUtf8("btnBackNewMulti"))
        self.verticalLayout_5.addWidget(self.btnBackNewMulti)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.label_22 = QtGui.QLabel(self.new_multi)
        self.label_22.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_7.addWidget(self.label_22)
        self.mainMenu.addWidget(self.new_multi)
        self.continue_multi = QtGui.QWidget()
        self.continue_multi.setObjectName(_fromUtf8("continue_multi"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.continue_multi)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lblMapContMulti = QtGui.QLabel(self.continue_multi)
        self.lblMapContMulti.setMinimumSize(QtCore.QSize(300, 0))
        self.lblMapContMulti.setText(_fromUtf8(""))
        self.lblMapContMulti.setObjectName(_fromUtf8("lblMapContMulti"))
        self.horizontalLayout_8.addWidget(self.lblMapContMulti)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_28 = QtGui.QLabel(self.continue_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_9.addWidget(self.label_28)
        self.lstChooseServerContMulti = QtGui.QListView(self.continue_multi)
        self.lstChooseServerContMulti.setObjectName(_fromUtf8("lstChooseServerContMulti"))
        self.verticalLayout_9.addWidget(self.lstChooseServerContMulti)
        self.btnContMulti = QtGui.QPushButton(self.continue_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnContMulti.setFont(font)
        self.btnContMulti.setObjectName(_fromUtf8("btnContMulti"))
        self.verticalLayout_9.addWidget(self.btnContMulti)
        self.btnBackContMulti = QtGui.QPushButton(self.continue_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnBackContMulti.setFont(font)
        self.btnBackContMulti.setObjectName(_fromUtf8("btnBackContMulti"))
        self.verticalLayout_9.addWidget(self.btnBackContMulti)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.label_27 = QtGui.QLabel(self.continue_multi)
        self.label_27.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_8.addWidget(self.label_27)
        self.mainMenu.addWidget(self.continue_multi)
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.mainMenu)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mainMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Cosmica Launcher", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; color:#ffaa00;\">C O S M I C A</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">LOGIN</span></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "Enter Email Address:", None))
        self.label_2.setText(_translate("MainWindow", "Enter Password:", None))
        self.btnLogin.setText(_translate("MainWindow", "Login to NeuroJump Servers", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffaa00;\">Register</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "Enter Email Address:", None))
        self.label_8.setText(_translate("MainWindow", "Enter Nickname:", None))
        self.label_9.setText(_translate("MainWindow", "Enter Password:", None))
        self.btnRegister.setText(_translate("MainWindow", "Register to NeuroJump Servers", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aaff;\">SINGLE PLAYER</span></p></body></html>", None))
        self.btnLoadNewSingle.setText(_translate("MainWindow", "Start a new Single Player Game", None))
        self.btnLoadContSingle.setText(_translate("MainWindow", "Continue an existing Single Player Game", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffaa00;\">MULTI PLAYER</span></p></body></html>", None))
        self.btnLoadJoinMulti.setText(_translate("MainWindow", "Join a Multiplayer Game", None))
        self.btnLoadHostMulti.setText(_translate("MainWindow", "Host a New Multiplayer Game Server", None))
        self.btnLoadContMulti.setText(_translate("MainWindow", "Continue an Existing Mulitplayer Server", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">Start a New</span></p><p align=\"center\"><span style=\" color:#00aaff;\">Single Player</span></p><p align=\"center\"><span style=\" color:#00aaff;\">Game</span></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffaa00;\">Choose a Map</span></p></body></html>", None))
        self.btnNewSingle.setText(_translate("MainWindow", "Start New Single Player Game", None))
        self.btnBackNewSingle.setText(_translate("MainWindow", "Go Back", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">Continue An</span></p><p align=\"center\"><span style=\" color:#00aaff;\">Existing</span></p><p align=\"center\"><span style=\" color:#00aaff;\">Single Player </span></p><p align=\"center\"><span style=\" color:#00aaff;\">Game</span></p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffaa00;\">Choose a Game</span></p></body></html>", None))
        self.btnContSingle.setText(_translate("MainWindow", "Continue Single Player Game", None))
        self.btnBackContSingle.setText(_translate("MainWindow", "Go Back", None))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">Choose an Active Game</span></p></body></html>", None))
        self.btnJoinMulti.setText(_translate("MainWindow", "Join Multiplayer Game", None))
        self.btnBackJoinMulti.setText(_translate("MainWindow", "Go Back", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffaa00;\">Join a</span></p><p align=\"center\"><span style=\" color:#ffaa00;\">Multiplayer</span></p><p align=\"center\"><span style=\" color:#ffaa00;\">Server</span></p></body></html>", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">Request Players</span></p><p align=\"center\"><span style=\" color:#00aaff;\">(neuroJump Nicknames)</span></p></body></html>", None))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">Choose a Map</span></p></body></html>", None))
        self.btnStartNewMulti.setText(_translate("MainWindow", "Start New Multiplayer Server", None))
        self.btnBackNewMulti.setText(_translate("MainWindow", "Go Back", None))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffaa00;\">Start a New </span></p><p align=\"center\"><span style=\" color:#ffaa00;\">MultiPlayer </span></p><p align=\"center\"><span style=\" color:#ffaa00;\">Server</span></p></body></html>", None))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">Choose Server</span></p></body></html>", None))
        self.btnContMulti.setText(_translate("MainWindow", "Continue Multiplayer Server", None))
        self.btnBackContMulti.setText(_translate("MainWindow", "Go Back", None))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffaa00;\">Continue</span></p><p align=\"center\"><span style=\" color:#ffaa00;\">Running</span></p><p align=\"center\"><span style=\" color:#ffaa00;\">a Multiplayer</span></p><p align=\"center\"><span style=\" color:#ffaa00;\">ServeR</span></p></body></html>", None))

import resources_rc
