# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Tue Feb 05 21:00:44 2019
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1064, 851)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8("#login_register {\n"
"    background-color: rgb(202, 202, 202);\n"
"}\n"
"\n"
"#choose_option {\n"
"    background-color: rgb(202, 202, 202);\n"
"}\n"
"#centralwidget {\n"
"    background-image: url(:/images/background.png);\n"
"}\n"
"#single_or_multi {\n"
"    background-color: rgb(161, 161, 161);\n"
"}\n"
"#new_single {\n"
"    background-color: rgb(161, 161, 161);\n"
"}\n"
"#continue_single {\n"
"    background-color: rgb(161, 161, 161);\n"
"}\n"
"#new_multi {\n"
"    background-color: rgb(161, 161, 161);\n"
"}\n"
"#continue_multi {\n"
"    background-color: rgb(161, 161, 161);\n"
"}\n"
"#join_multi {\n"
"    background-color: rgb(161, 161, 161);\n"
"}\n"
"\n"
"\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayout = QtGui.QFormLayout(self.centralwidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_3)
        self.mainMenu = QtGui.QStackedWidget(self.centralwidget)
        self.mainMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.mainMenu.setObjectName(_fromUtf8("mainMenu"))
        self.login_register = QtGui.QWidget()
        self.login_register.setObjectName(_fromUtf8("login_register"))
        self.formLayout_2 = QtGui.QFormLayout(self.login_register)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_4)
        self.label = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.txtEmail = QtGui.QLineEdit(self.login_register)
        self.txtEmail.setObjectName(_fromUtf8("txtEmail"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtEmail)
        self.label_2 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txtPassword = QtGui.QLineEdit(self.login_register)
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtPassword)
        self.btnLogin = QtGui.QPushButton(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName(_fromUtf8("btnLogin"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.btnLogin)
        self.label_7 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.txtNewEmail = QtGui.QLineEdit(self.login_register)
        self.txtNewEmail.setObjectName(_fromUtf8("txtNewEmail"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.txtNewEmail)
        self.label_8 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txtNickname = QtGui.QLineEdit(self.login_register)
        self.txtNickname.setObjectName(_fromUtf8("txtNickname"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.txtNickname)
        self.label_9 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.txtNewPassword = QtGui.QLineEdit(self.login_register)
        self.txtNewPassword.setObjectName(_fromUtf8("txtNewPassword"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.txtNewPassword)
        self.btnRegister = QtGui.QPushButton(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnRegister.setFont(font)
        self.btnRegister.setObjectName(_fromUtf8("btnRegister"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.btnRegister)
        self.label_6 = QtGui.QLabel(self.login_register)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_6)
        self.mainMenu.addWidget(self.login_register)
        self.single_or_multi = QtGui.QWidget()
        self.single_or_multi.setObjectName(_fromUtf8("single_or_multi"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.single_or_multi)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.single_player_layout = QtGui.QVBoxLayout()
        self.single_player_layout.setObjectName(_fromUtf8("single_player_layout"))
        self.label_5 = QtGui.QLabel(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.single_player_layout.addWidget(self.label_5)
        self.pushButton = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.single_player_layout.addWidget(self.pushButton)
        self.pushButton_4 = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.single_player_layout.addWidget(self.pushButton_4)
        self.horizontalLayout.addLayout(self.single_player_layout)
        self.multi_player_layout = QtGui.QVBoxLayout()
        self.multi_player_layout.setObjectName(_fromUtf8("multi_player_layout"))
        self.label_10 = QtGui.QLabel(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.multi_player_layout.addWidget(self.label_10)
        self.pushButton_2 = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.multi_player_layout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.multi_player_layout.addWidget(self.pushButton_3)
        self.pushButton_5 = QtGui.QPushButton(self.single_or_multi)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.multi_player_layout.addWidget(self.pushButton_5)
        self.horizontalLayout.addLayout(self.multi_player_layout)
        self.mainMenu.addWidget(self.single_or_multi)
        self.new_single = QtGui.QWidget()
        self.new_single.setObjectName(_fromUtf8("new_single"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.new_single)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = QtGui.QLabel(self.new_single)
        self.label_11.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_12 = QtGui.QLabel(self.new_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_3.addWidget(self.label_12)
        self.lstChooseMap = QtGui.QListView(self.new_single)
        self.lstChooseMap.setObjectName(_fromUtf8("lstChooseMap"))
        self.verticalLayout_3.addWidget(self.lstChooseMap)
        self.btnStartSingle = QtGui.QPushButton(self.new_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnStartSingle.setFont(font)
        self.btnStartSingle.setObjectName(_fromUtf8("btnStartSingle"))
        self.verticalLayout_3.addWidget(self.btnStartSingle)
        self.btnBackFromNewSingle = QtGui.QPushButton(self.new_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.btnBackFromNewSingle.setFont(font)
        self.btnBackFromNewSingle.setObjectName(_fromUtf8("btnBackFromNewSingle"))
        self.verticalLayout_3.addWidget(self.btnBackFromNewSingle)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblMapImage = QtGui.QLabel(self.new_single)
        self.lblMapImage.setMinimumSize(QtCore.QSize(300, 0))
        self.lblMapImage.setText(_fromUtf8(""))
        self.lblMapImage.setObjectName(_fromUtf8("lblMapImage"))
        self.verticalLayout_2.addWidget(self.lblMapImage)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.mainMenu.addWidget(self.new_single)
        self.continue_single = QtGui.QWidget()
        self.continue_single.setObjectName(_fromUtf8("continue_single"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.continue_single)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_13 = QtGui.QLabel(self.continue_single)
        self.label_13.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_14 = QtGui.QLabel(self.continue_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Terminator Two"))
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_6.addWidget(self.label_14)
        self.lstChooseSingleGame = QtGui.QListWidget(self.continue_single)
        self.lstChooseSingleGame.setObjectName(_fromUtf8("lstChooseSingleGame"))
        self.verticalLayout_6.addWidget(self.lstChooseSingleGame)
        self.pushButton_7 = QtGui.QPushButton(self.continue_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_6.addWidget(self.pushButton_7)
        self.pushButton_6 = QtGui.QPushButton(self.continue_single)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("RowdyHeavy"))
        font.setPointSize(9)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.lblMapImage2 = QtGui.QLabel(self.continue_single)
        self.lblMapImage2.setMinimumSize(QtCore.QSize(300, 0))
        self.lblMapImage2.setText(_fromUtf8(""))
        self.lblMapImage2.setObjectName(_fromUtf8("lblMapImage2"))
        self.horizontalLayout_4.addWidget(self.lblMapImage2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.mainMenu.addWidget(self.continue_single)
        self.join_multi = QtGui.QWidget()
        self.join_multi.setObjectName(_fromUtf8("join_multi"))
        self.mainMenu.addWidget(self.join_multi)
        self.new_multi = QtGui.QWidget()
        self.new_multi.setObjectName(_fromUtf8("new_multi"))
        self.mainMenu.addWidget(self.new_multi)
        self.continue_multi = QtGui.QWidget()
        self.continue_multi.setObjectName(_fromUtf8("continue_multi"))
        self.mainMenu.addWidget(self.continue_multi)
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.mainMenu)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mainMenu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Cosmica Launcher", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; color:#ffaa00;\">C O S M I C A</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "Login:", None))
        self.label.setText(_translate("MainWindow", "Enter Email Address:", None))
        self.label_2.setText(_translate("MainWindow", "Enter Password:", None))
        self.btnLogin.setText(_translate("MainWindow", "Login", None))
        self.label_7.setText(_translate("MainWindow", "Enter Email Address:", None))
        self.label_8.setText(_translate("MainWindow", "Enter Nickname:", None))
        self.label_9.setText(_translate("MainWindow", "Enter Password:", None))
        self.btnRegister.setText(_translate("MainWindow", "Register to NeuroJump", None))
        self.label_6.setText(_translate("MainWindow", "Register:", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aaff;\">SINGLE PLAYER</span></p></body></html>", None))
        self.pushButton.setText(_translate("MainWindow", "Start a new Single Player Game", None))
        self.pushButton_4.setText(_translate("MainWindow", "Continue an existing Single Player Game", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffaa00;\">MULTI PLAYER</span></p></body></html>", None))
        self.pushButton_2.setText(_translate("MainWindow", "Join a Multiplayer Game", None))
        self.pushButton_3.setText(_translate("MainWindow", "Host a New Multiplayer Game Server", None))
        self.pushButton_5.setText(_translate("MainWindow", "Continue an Existing Mulitplayer Server", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">Start a New</span></p><p align=\"center\"><span style=\" color:#00aaff;\">Single Player</span></p><p align=\"center\"><span style=\" color:#00aaff;\">Game</span></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffaa00;\">Choose a Map</span></p></body></html>", None))
        self.btnStartSingle.setText(_translate("MainWindow", "Start New Single Player Game", None))
        self.btnBackFromNewSingle.setText(_translate("MainWindow", "Go Back", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">Continue An</span></p><p align=\"center\"><span style=\" color:#00aaff;\">Existing</span></p><p align=\"center\"><span style=\" color:#00aaff;\">Single Player </span></p><p align=\"center\"><span style=\" color:#00aaff;\">Game</span></p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffaa00;\">Choose a Game</span></p></body></html>", None))
        self.pushButton_7.setText(_translate("MainWindow", "Continue Single Player Game", None))
        self.pushButton_6.setText(_translate("MainWindow", "Go Back", None))

import resources_rc
